### ISSUE TITLE
OpenTracingSpan implement should avoid using cached context 

### ISSUE THREAD

**Issue by AshokVardhanM** [helidon-io/helidon#7161]
[//]: # "Please remove these comments"
[//]: # "Provide a general summary of the issue in the Title above"

## Environment Details
* Helidon Version: 3.2.1
* Helidon SE or Helidon MP 
* JDK version: 17
* OS:
* Docker version (if applicable):

----------

## Problem Description
In the current implementation of OpenTracingSpan , it caches OpenTracingContext context  in the constructor as shown below.

OpenTracingSpan(Tracer tracer, io.opentracing.Span delegate) {
        this.tracer = tracer;
        this.delegate = delegate;
        this.context = new OpenTracingContext(delegate.context());
    }

This approach can create issues with underlying wrapped span's context (delegate.context()) changes at a later point in time depending on the OpenTracing implementation which is used as delegate. 
 for those cases  the current implementation below will end up returning a stale context.

@Override
    public SpanContext context() {
        return context;
    }

This also impacts baggage propagation as baggage items added to the delegate at the later point are not available in the cached context. So the ask is to change the implementation of context() method as below to return the updated context as below.

@Override
    public SpanContext context() {
        return new OpenTracingContext(delegate.context());
    }
    
  This change helps address the stale context and the baggage issues.

**Comment by dalexandrov** [comment]
We are aware of this implementation, But this is how it works in Reactive environment in Helidon SE, @tomas-langer please confirm. 
Baggage issues are already addressed in Helidon 3.2.2. Should be used with `helidon-tracing-jaeger`.

**Comment by RickyFrost** [comment]
This seems a lot like 6970 which was said to be fixed as part of 6987, but was in fact not fixed at all.
The change in 6987 was only to OpenTelemetrySpan, not OpenTracingSpan.

**Comment by RickyFrost** [comment]
I don't understand how this is closed when 7167 is still open.
