### ISSUE TITLE
4.x: WithSpanWithExplicitAppTest fails (always) on local machine

### ISSUE THREAD

**Issue by tomas-langer** [helidon-io/helidon#8249]
The following config exists in pom:
```xml
<!-- The test times out in the pipeline, even with very long retry delays. -->
<excludes>
    <exclude>**/WithSpanWithExplicitAppTest.java</exclude>
</excludes>
```

Yet I have this test failing on local machine consistently (tried 10 times, could not pass it). Maybe there is a real problem with the test, not an intermittent issue...

Could reproduce when running from IDE - the test passes if run as a single test, but fails if run with other tests in the package.

Failures:
```
[INFO]
[ERROR] Failures:
[ERROR]   WithSpanWithExplicitAppTest.testExplicitAppSpanNameFromPath:37->WithSpanTestBase.testSpanNameFromPath:67 Expected span count
Expected: an iterable with size <2>
     but: iterable size was <0>
[ERROR]   WithSpanWithExplicitAppTest.testExplicitAppSpanNameFromPath:37->WithSpanTestBase.testSpanNameFromPath:67 Expected span count
Expected: an iterable with size <2>
     but: iterable size was <0>
```

**Comment by tomas-langer** [comment]
The following fixes the test (running each test in its own VM):
```xml
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <configuration>
                    <reuseForks>false</reuseForks>
                </configuration>
            </plugin>
```

**Comment by tomas-langer** [comment]
So the problem is definitely interference between tests. 
Possibility - is it maybe possible that the OpenTelemetry discovers the exporter just once? Then it would use the first exporter from the first CDI that is run, and all subsequent tests would get a wrong instance of the exporter?

**Comment by tjquinno** [comment]
On your system do you know if it is necessary to run _every_ test in its own JVM or just the `WithSpanWithExplicitAppTest` one?

**Comment by tjquinno** [comment]
I was seeing failures in the pipeline but not locally. I had a PR open to fix that which was recently approved and I just merged it.

Can you please fetch `main` again and retry?

**Comment by tjquinno** [comment]
@tomas-langer Do you still see the problem after the merge of the PR I mentioned earlier?

**Comment by tomas-langer** [comment]
Works on command line, still fails when I run all the tests in IDE (ie. all tests in package) - this may be that the IDE does not honor the exact configuration in pom file.

**Comment by tomas-langer** [comment]
When I switch to a fork mode with fork per method, it works in IDE as well (my original workaround)
