### ISSUE TITLE
4.x - OidcCdiExtension should not require configuration

### ISSUE THREAD

**Issue by romain-grecourt** [helidon-io/helidon#8493]
## Environment Details
* Helidon Version: 4.0.6
* Helidon MP

----------

## Problem Description

If you have `io.helidon.microprofile:helidon-microprofile-oidc` in your class-path, it should only activate if the required configuration is present.

Currently (4.0.6), if there is no security configuration the server startup fails:

```
Exception in thread "main" io.helidon.config.MissingValueException: Requested value for configuration key '' is not present in the configuration.
	at io.helidon.config.MissingValueException.create(MissingValueException.java:44)
	at io.helidon.config.ConfigValue.lambda$get$0(ConfigValue.java:93)
	at java.base/java.util.Optional.orElseThrow(Optional.java:403)
	at io.helidon.config.ConfigValue.get(ConfigValue.java:93)
	at io.helidon.security.providers.oidc.OidcFeature$Builder.findMyKey(OidcFeature.java:657)
	at io.helidon.security.providers.oidc.OidcFeature$Builder.config(OidcFeature.java:715)
	at io.helidon.security.providers.oidc.OidcFeature.create(OidcFeature.java:209)
	at io.helidon.microprofile.oidc.OidcCdiExtension.registerOidcSupport(OidcCdiExtension.java:48)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
``` 

## Steps to reproduce

Add the following dependency to your pom.xml, make sure there is no security configuration.

```xml
<dependency>
    <groupId>io.helidon.microprofile</groupId>
    <artifactId>helidon-microprofile-oidc</artifactId>
</dependency>
```

**Comment by romain-grecourt** [comment]
@tomas-langer please confirm is this is fixed with the changes made for these:
- https://github.com/helidon-io/helidon/pull/8521
- https://github.com/helidon-io/helidon/pull/8520

**Comment by tomas-langer** [comment]
You need to add `enabled: false`, otherwise this will most likely still fail (would need to test it to be sure)
